nodeLinker: node-modules
enableImmutableInstalls: false
enableImmutableCache: false
supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
